version: 2.1
jobs:
  build:
    docker:
      - image: 'zeekozhu/aspnetcore-build-yarn:3.0-chromium'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v1-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          keys:
            - npm-cache-v1-{{ checksum "yarn.lock" }}
      - run: yarn build
  test:
    docker:
      - image: 'zeekozhu/aspnetcore-build-yarn:3.0-chromium'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v1-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn run test:ci
      - restore_cache:
          keys:
            - npm-cache-v1-{{ checksum "yarn.lock" }}
workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - test:
        requires:
          build
