version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: 'zeekozhu/aspnetcore-build-yarn:3.0-chromium'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v1-{{ checksum "yarn.lock" }}
            - npm-cache-v1-
      - run: yarn
      - save_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build
  test:
    docker:
      - image: 'zeekozhu/aspnetcore-build-yarn:3.0-chromium'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v1-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn run test:ci
      - codecov/upload:
        file: coverage/notify-lite/lcov.info
workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - test:
          requires:
            - build
